In [1]:
 import torch
 import torch.nn as nn
 import torch.utils.data as data
 from names_loader import NameData
 from model import RNN
 from torch.autograd import Variable

## Lab 3 Introduction
So far, we've worked on an image classification task on Norb dataset and a semantic segmentation task on PASCAL VOC 2007 dataset. In today's lab, we'll build on the known concepts to construct a Recurrent Neural Network (RNN). The problem we'll try to solve is a toy problem: given the last name of a person, predict the country of origin!

For this, we have provided a dataset in `data/` directory. The idea is to build an RNN that sees one __letter__ at a time and when all the letters are seen, we ask it to predict the country of origin of the name. We have, like last lab, three files to write: the model, the dataloader, and this training file. 

### Setting the dataloader
We have written a dataset class for you (if you want to go back early) in `names_loader.py`. You may choose to write your own dataset class if you wish. Let's try to create two dataloader objects, one for training and one for testing. Once that is done, have a look into what the dataloader produces. You'll find the input of size `(batch_size, 18, 57)`. 18 is the maximum length of the names in the dataset. If a name is shorter than 18 letters, it is left padded. 57 is the number of characters in the alphabet. The last dimension is a one-hot vector of the character.

In [2]:
# Initializing the dataset objects
dataset_train = NameData('./data', 'train')
dataset_val = NameData('./data', 'val')

# Initializing the dataloader object. 
dataloader_train = data.DataLoader(
                dataset_train, batch_size = 8, 
                shuffle = True, num_workers = 4)

dataloader_val = data.DataLoader(
                dataset_val, batch_size = 1, 
                shuffle = False, num_workers = 1)

print(dataset_train.n_categories)
# Let's test the network's outputs
name = 'krizhevsky'
encoding = dataset_train.nameToTensor(name)
print(encoding)

18
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [3]:
# Let's investigate the output of the dataloader
for i, (input, target) in enumerate(dataloader_train):
    print(target.size())
    if i > 10:
        break

torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])
torch.Size([8, 1])


### Loading the model, criterion and the optimizer
Let's try to load the network now. This should be routine by now! Also convert the model and criterion into cuda variables.

In [4]:
# Initialize the network. Hidden size: 1024.
# 57 is the length of the one-hot-encoded input at each timestep
model = RNN(57, 1024, dataset_train.n_categories)
criterion = nn.CrossEntropyLoss()

# Convert model and criterion into cuda here
model.cuda()
criterion.cuda()

# Print the RNN
print(model)

RNN(
  (i2h): Linear(in_features=1081, out_features=1024, bias=True)
  (h2o): Linear(in_features=1024, out_features=18, bias=True)
  (i2o): Linear(in_features=1081, out_features=18, bias=True)
  (softmax): LogSoftmax()
)


__One Question that no one* asked:__ Where's the softmax happening? We never wrote a softmax layer in our neural network. Then how come we're still managing with CrossEntropy Loss?

__One more question that no one asked:__ Why are the labels not one hot encoded for cross entropy loss?

Let's also initialize an optimizer for the task. You're free to make your hyperparameter decisions in this regard

In [5]:
optimizer = torch.optim.SGD(model.parameters(), 0.005)

We're ready to train our first RNN. But before we do that, we need to write the train function that iterates over the data, forward props, computes the losses, backprops and  finally updates. 

In [6]:
def train(epoch, dataloader, model, criterion, optimizer, categories, split = 'train'):
    # Useful for some book-keeping 
    loss_meter, acc_meter, count = 0, 0, 0

    # Call model.eval if we're doing validation 
    if split == 'valid' or split == 'test':
         model = model.eval()

    for i, (input, target) in enumerate(dataloader):
        input = Variable(input.float()).cuda()
        target = Variable(target.reshape(-1,)).long().cuda()
    
        # Initializing the hidden state
        batch_size = input.size(0)
        hidden = Variable(model.init_hidden(batch_size)).cuda()

        # seq_len = input.size(1)
        model.zero_grad()
        
        for f in range(input.size(1)):
            output, hidden = model(input[:,f,:], hidden)

        loss = criterion(output, target)
        acc = accuracy(output, target)
        loss_meter += loss.data.cpu().numpy()
        acc_meter += acc

        if split == 'train':
            optimizer.zero_grad()
            loss.backward()
            # A must-do step to avoid the exploding gradient problem.
            # We're restricting the norm of the the gradients to less than 5.
            # The effects of this may not be visible in this toy problem, but
            # can be seen when dealing with more complicated problems.
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5)
            optimizer.step()

        count += 1
        # print('loss at epoch ', str(epoch), ' iteration ', str(i), ' is: ', loss.data.cpu().numpy())
        if i % 500 == 0:
            print(split + ' epoch ', epoch, ' iteration ', i, ' loss is : ', 
                  loss_meter / count, ' accuracy is  ', acc_meter / count)

    print(split + ' loss at epoch ', str(epoch), ' is: ', loss_meter / count)



Let's also write a funciton `accuracy` that computes the accuracy of our predictions.

In [7]:
 def accuracy(pred, gt):
     pred = pred.argmax(1)
     correct, count = 0, 0
     for i in range(pred.size(0)):
         if pred[i] == gt[i]:
             correct += 1
         count += 1
     accuracy = correct / count
     return accuracy

Now is the time to enter the training loop. We'll iterate for `n_epoch` times and validate after every second epoch:

In [8]:
n_epoch = 3
categories = dataset_train.all_categories

for i in range(n_epoch):
    train(i, dataloader_train, model, criterion, optimizer, categories, 'train')
    if i % 2 == 1:
     print('***************** Validation Loop Starts *********************')
     train(i, dataloader_val, model, criterion, optimizer, categories, 'val')
     print('***************** Validation Loop Ends *********************')


train epoch  0  iteration  0  loss is :  2.8879857063293457  accuracy is   0.0
train epoch  0  iteration  500  loss is :  2.0999727074257626  accuracy is   0.4540918163672655
train epoch  0  iteration  1000  loss is :  1.947241179890685  accuracy is   0.4621628371628372
train epoch  0  iteration  1500  loss is :  1.8824079184632234  accuracy is   0.4624417055296469
train loss at epoch  0  is:  1.846264190308253
train epoch  1  iteration  0  loss is :  1.81686270236969  accuracy is   0.5
train epoch  1  iteration  500  loss is :  1.6388645449322379  accuracy is   0.48577844311377244
train epoch  1  iteration  1000  loss is :  1.647268255928775  accuracy is   0.47977022977022976
train epoch  1  iteration  1500  loss is :  1.6392047827558307  accuracy is   0.4814290473017988
train loss at epoch  1  is:  1.631337331787745
***************** Validation Loop Starts *********************
val epoch  1  iteration  0  loss is :  0.365123987197876  accuracy is   1.0
val epoch  1  iteration  500  l

### Last thing to do for the workshop
Let's test the model now. This is simple. Think of any name for testing, encode it as per the RNN's requirements and forward prop it. Let's do that now:

In [16]:
# Let's test the network's outputs
name = 'Smith'
encoding = dataset_train.nameToTensor(name)
print(encoding)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [17]:
print(encoding.shape)

torch.Size([18, 57])


In [18]:
encoding = encoding.reshape(1,18,57)

In [19]:
# Should probably have wrapped this in a function, but here's the dirty forward pass through the RNN
input = Variable(encoding.float()).cuda()

# Initializing the hidden state
batch_size = input.size(0)
hidden = Variable(model.init_hidden(batch_size)).cuda()

for f in range(input.size(1)):
    output, hidden = model(input[:,f,:], hidden)

print(output)
print(output.argmax())

tensor([[-0.3435,  0.5734, -0.8832,  2.1969, -0.3696, -1.4263,  1.1668, -0.3840,
          2.3474, -1.2357, -0.4289,  1.4868, -1.3425, -0.3231,  0.5616, -1.1998,
          0.3409, -0.6710]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor(8, device='cuda:0')


In [20]:
# Let's see what are the language indices
for i in range(len(dataset_train.all_categories)):
    print(i, dataset_train.all_categories[i])

['Spanish', 'German', 'Polish', 'Russian', 'Chinese', 'Portuguese', 'Japanese', 'French', 'English', 'Korean', 'Irish', 'Arabic', 'Vietnamese', 'Dutch', 'Italian', 'Scottish', 'Czech', 'Greek']
0 Spanish
1 German
2 Polish
3 Russian
4 Chinese
5 Portuguese
6 Japanese
7 French
8 English
9 Korean
10 Irish
11 Arabic
12 Vietnamese
13 Dutch
14 Italian
15 Scottish
16 Czech
17 Greek
